import { and,asc,eq,sql } from 'drizzle-orm'; import { createDatabase } from '@/app/db/client'; import { addresses } from '@/app/db/schema';
export type AddressInput={receiverName:string;mobile:string;province:string;city:string;address:string;plaque?:string|null;unit?:string|null;postalCode:string};
const fields={id:addresses.id,receiverName:addresses.receiverName,mobile:addresses.mobile,province:addresses.province,city:addresses.city,address:addresses.address,plaque:addresses.plaque,unit:addresses.unit,postalCode:addresses.postalCode,isDefault:addresses.isDefault};
export class AddressRepository{
 private db(){return createDatabase()}
 list(userId:string){return this.db().select(fields).from(addresses).where(eq(addresses.userId,userId)).orderBy(asc(addresses.createdAt));}
 async create(userId:string,input:AddressInput){const existing=await this.db().$count(addresses,eq(addresses.userId,userId));const[row]=await this.db().insert(addresses).values({...input,userId,isDefault:existing===0}).returning(fields);return row;}
 async update(userId:string,id:string,input:Partial<AddressInput>){const[row]=await this.db().update(addresses).set({...input,updatedAt:new Date()}).where(and(eq(addresses.id,id),eq(addresses.userId,userId))).returning(fields);return row;}
 async remove(userId:string,id:string){const result=await this.db().execute(sql`WITH deleted AS (DELETE FROM addresses WHERE id=${id} AND user_id=${userId} RETURNING is_default), replacement AS (SELECT id FROM addresses WHERE user_id=${userId} ORDER BY created_at LIMIT 1) UPDATE addresses SET is_default=true, updated_at=now() WHERE id=(SELECT id FROM replacement) AND EXISTS(SELECT 1 FROM deleted WHERE is_default=true) RETURNING id`);return result.rowCount!==0||(await this.db().$count(addresses,and(eq(addresses.userId,userId),eq(addresses.id,id))))===0;}
 async setDefault(userId:string,id:string){const owned=await this.db().$count(addresses,and(eq(addresses.id,id),eq(addresses.userId,userId)));if(!owned)return undefined;await this.db().batch([this.db().update(addresses).set({isDefault:false,updatedAt:new Date()}).where(eq(addresses.userId,userId)),this.db().update(addresses).set({isDefault:true,updatedAt:new Date()}).where(and(eq(addresses.id,id),eq(addresses.userId,userId)))]);const[row]=await this.db().select(fields).from(addresses).where(and(eq(addresses.id,id),eq(addresses.userId,userId)));return row;}
}
